name: Posting
on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes
  workflow_dispatch:


jobs:
  post_job:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run posting script
        env:
          ACCOUNTS: ${{ vars.ACCOUNTS }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_IDS: ${{ vars.GIST_IDS }}
          SERVER_ADS: ${{ vars.SERVER_ADS }}
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID_LIST: ${{ secrets.NOTION_DATABASE_ID_LIST }}
          GIST_ID: ${{ secrets.GIST_ID }}
          

        run: |
          python Posting/mainscript.py
