name: Posting
on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes
  workflow_dispatch:


jobs:
  post_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run posting script
        env:
          ACCOUNTS: ${{ secrets.ACCOUNTS }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          CATHEGORIES: ${{ vars.CATHEGORIES }}
          SERVER_ADS: ${{ vars.SERVER_ADS }}

        run: |
          python Posting/mainscript.py

      - name: Commit and push TrackerFile update
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Posting/tracker.json
          git commit -m "Update TrackerFile automatically"
          git push
